---
- name: Respaldo de Código Estandarizado - DocSolutions
  hosts: 172.17.120.10
  gather_facts: yes
  vars:
    path_apps_prod: "C:\\APPS_PROD"
    temp_mirror: "C:\\Windows\\Temp\\Mirror_Apps"
    temp_zip_code: "C:\\Windows\\Temp\\codigo_produccion.zip"
    base_nfs: "/mnt/respaldos_externos"
    dest_codigo: "{{ base_nfs }}/codigo/{{ inventory_hostname }}/{{ ansible_date_time.date }}"

  tasks:
    - name: 1. Limpiar espejo previo si existe
      win_file:
        path: "{{ temp_mirror }}"
        state: absent

    - name: 2. Crear espejo de carpetas (Excluyendo archivos .log)
      win_shell: |
        Copy-Item -Path "{{ path_apps_prod }}\*" -Destination "{{ temp_mirror }}" -Recurse -Exclude *.log -ErrorAction SilentlyContinue

    - name: 3. Comprimir el espejo (Solo src y dest)
      community.windows.win_zip:
        src: "{{ temp_mirror }}\\"
        dest: "{{ temp_zip_code }}"

    - name: 4. Transferir Código al NFS
      fetch:
        src: "{{ temp_zip_code }}"
        dest: "{{ dest_codigo }}/codigo_apps.zip"
        flat: yes

    - name: 5. Limpieza de temporales
      win_file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ temp_mirror }}"
        - "{{ temp_zip_code }}"