---
- name: Respaldo Dinámico Multiserver (DocSolutions)
  hosts: Servidores_Apps
  gather_facts: yes
  vars:
    # Regex para ignorar archivos temporales y logs
    regex_sin_logs: '^(?!.*(\.log|\.txt|\.tmp|\.bak)$).*$'
    
    # Directorios del Sistema Operativo que NO queremos tocar
    carpetas_excluidas:
      - "C:\\Windows"
      - "C:\\Program Files"
      - "C:\\Program Files (x86)"
      - "C:\\Users"
      - "C:\\$Recycle.Bin"
      - "C:\\System Volume Information"
      - "C:\\PerfLogs"
      - "C:\\ProgramData"

    central_backup_path: "/backups/Apps_Prod"
    temp_zip: "C:\\Windows\\Temp\\backup_apps.zip"

  tasks:
    - name: 1. Obtener letras de unidad vía PowerShell
      win_shell: |
        Get-PSDrive -PSProvider FileSystem | Select-Object -ExpandProperty Root
      register: drive_out

    - name: 2. Normalizar lista de unidades
      set_fact:
        active_drives: "{{ drive_out.stdout_lines | map('trim') | list }}"

    - name: 3. Buscar archivos de aplicación (Excluyendo SO y Logs)
      win_find:
        paths: "{{ active_drives }}"
        patterns: "{{ regex_sin_logs }}"
        exclude_directories: "{{ carpetas_excluidas }}"
        use_regex: yes
        recurse: yes
        file_type: file
      register: app_files

    - name: 4. Comprimir hallazgos
      community.windows.win_zip:
        dest: "{{ temp_zip }}"
        sources: "{{ item.path }}"
        action: add
      loop: "{{ app_files.files }}"
      when: app_files.matched > 0
      no_log: true

    - name: 5. Transferir a dsb57 (Estructura Dinámica)
      fetch:
        src: "{{ temp_zip }}"
        dest: "{{ central_backup_path }}/{{ inventory_hostname }}/{{ ansible_date_time.date }}/backup_docsolutions.zip"
        flat: yes
      when: app_files.matched > 0

    - name: 6. Limpieza de residuos en Windows
      win_file:
        path: "{{ temp_zip }}"
        state: absent