---
- name: Respaldo de Código Estandarizado - DocSolutions
  hosts: 172.17.120.10
  gather_facts: yes
  vars:
    path_apps_prod: "C:\\APPS_PROD"
    temp_mirror: "C:\\Windows\\Temp\\Mirror_Apps"
    temp_zip_code: "C:\\Windows\\Temp\\codigo_produccion.zip"
    # Ruta que apunta al Bind Mount para no saturar /var local
    dest_codigo: "/var/lib/awx/projects/nfs_docsol/codigo/{{ inventory_hostname }}/{{ ansible_date_time.date }}"

  tasks:
    - name: 1. Limpieza y creación de espejo
      win_file:
        path: "{{ temp_mirror }}"
        state: "{{ item }}"
      loop: [absent, directory]

    - name: 2. Robocopy (La forma segura de excluir logs)
      win_shell: |
        robocopy "{{ path_apps_prod }}" "{{ temp_mirror }}" /E /XF *.log /R:2 /W:5
      register: robocopy_status
      failed_when: robocopy_status.rc > 8

    - name: 3. Comprimir (SOLO src y dest para evitar errores de versión)
      community.windows.win_zip:
        src: "{{ temp_mirror }}\\"
        dest: "{{ temp_zip_code }}"

    - name: 4. Transferencia al NFS (Vía Bind Mount)
      fetch:
        src: "{{ temp_zip_code }}"
        dest: "{{ dest_codigo }}/codigo_apps.zip"
        flat: yes

    - name: 5. Limpieza final en Windows
      win_file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ temp_mirror }}"
        - "{{ temp_zip_code }}"