---
- name: Respaldo y Rotación de Logs - DocSolutions
  hosts: 172.17.120.10
  vars:
    path_apps_prod: "C:\\APPS_PROD"
    temp_logs_dir: "C:\\Windows\\Temp\\Logs_To_Export"
    temp_zip_logs: "C:\\Windows\\Temp\\logs_final.zip"
    base_nfs: "/mnt/respaldos_externos"
    dest_logs: "{{ base_nfs }}/logs/{{ inventory_hostname }}/{{ ansible_date_time.date }}"

  tasks:
    - name: 1. Crear carpeta temporal para evitar bloqueos
      win_file:
        path: "{{ temp_logs_dir }}"
        state: directory

    - name: 2. Copiar logs (Ignorando los que están bloqueados actualmente)
      win_shell: |
        Get-ChildItem -Path "{{ path_apps_prod }}" -Filter *.log -Recurse | ForEach-Object {
            Copy-Item $_.FullName -Destination "{{ temp_logs_dir }}" -ErrorAction SilentlyContinue
        }

    - name: 3. Comprimir los logs copiados
      community.windows.win_zip:
        src: "{{ temp_logs_dir }}\\"
        dest: "{{ temp_zip_logs }}"
      register: zip_status

    - name: 4. Transferir a NFS
      fetch:
        src: "{{ temp_zip_logs }}"
        dest: "{{ dest_logs }}/logs_apps.zip"
        flat: yes
      when: zip_status.success

    - name: 5. ELIMINAR LOGS ANTIGUOS (Limpieza de 7 días)
      win_shell: |
        Get-ChildItem -Path "{{ path_apps_prod }}" -Filter *.log -Recurse | Where-Object { $_.LastWriteTime -lt (Get-Date).AddDays(-7) } | Remove-Item -Force -ErrorAction SilentlyContinue

    - name: 6. Limpieza de temporales
      win_file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ temp_logs_dir }}"
        - "{{ temp_zip_logs }}"